spring.application.name=smart_building

# DataSource
spring.datasource.url=jdbc:mariadb://localhost:3306/smart_building
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
#
#
#spring.security.user.name=root
#spring.security.user.password=root

jwt.secret=2XZCFnmx0gac6Obn7LVsXtxpT36eCKJBGEbXg3luFuN2
jwt.expiration=360000000
logging.level.org.springframework.security=DEBUG


admin.username=admin
admin.password=admin

#
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG

app.simulator.enabled=true
app.simulator.interval-ms=5000
logging.level.com.rdhxb.smart_building.simulator=DEBUG
