package com.rdhxb.smart_building.eventlog.entity;

public enum EventType {
    CREATED, UPDATED, DELETED,

    DEVICE_STATE_CHANGED,

    SENSOR_THRESHOLD_EXCEEDED,
    MOTION_DETECTED,
    DOOR_OPENED, DOOR_CLOSED,

    AUTOMATION_TRIGGERED,
    SCHEDULE_EXECUTED,

    USER_LOGIN, USER_LOGOUT, USER_LOGIN_FAILED,

    ALERT_RAISED, ALERT_RESOLVED
}
